/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'chat.avails.scheduling.availability'

export { $nsid }

/** A participant's standing availability for a specific group's calls. Self-hosted in the participant's own PDS. */
type Main = {
  $type: 'chat.avails.scheduling.availability'

  /**
   * The single group this offer is for.
   */
  scope: Scope
  pattern: Pattern

  /**
   * IANA timezone, e.g. America/New_York. Windows are interpreted in this zone.
   */
  timezone: string

  /**
   * confirm = ask me before booking; auto = an agent may book into my windows without confirming each time.
   */
  trust: 'confirm' | 'auto' | l.UnknownString

  /**
   * Expiry. Short by default so the pattern decays.
   */
  validUntil?: l.DatetimeString
  createdAt: l.DatetimeString
  updatedAt?: l.DatetimeString
}

export type { Main }

/** A participant's standing availability for a specific group's calls. Self-hosted in the participant's own PDS. */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    scope: /*#__PURE__*/ l.ref<Scope>((() => scope) as any),
    pattern: /*#__PURE__*/ l.ref<Pattern>((() => pattern) as any),
    timezone: /*#__PURE__*/ l.string(),
    trust: /*#__PURE__*/ l.string<{ knownValues: ['confirm', 'auto'] }>(),
    validUntil: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
    updatedAt: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ format: 'datetime' }),
    ),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type Scope = {
  $type?: 'chat.avails.scheduling.availability#scope'
  type: 'atproto-list' | 'ca-community' | 'ca-event' | l.UnknownString

  /**
   * For atproto-list: an at:// URI of an app.bsky.graph.list. For ca-community: the community-admin community id. For ca-event: the stable event DID.
   */
  value: string
}

export type { Scope }

const scope = /*#__PURE__*/ l.typedObject<Scope>(
  $nsid,
  'scope',
  /*#__PURE__*/ l.object({
    type: /*#__PURE__*/ l.string<{
      knownValues: ['atproto-list', 'ca-community', 'ca-event']
    }>(),
    value: /*#__PURE__*/ l.string(),
  }),
)

export { scope }

type Pattern = {
  $type?: 'chat.avails.scheduling.availability#pattern'

  /**
   * Recurring weekly windows.
   */
  weekly: Window[]

  /**
   * Reserved for explicit one-off date ranges (Phase 1.1). Stored, not yet surfaced.
   */
  dateRanges?: DateRange[]
}

export type { Pattern }

const pattern = /*#__PURE__*/ l.typedObject<Pattern>(
  $nsid,
  'pattern',
  /*#__PURE__*/ l.object({
    weekly: /*#__PURE__*/ l.array(
      /*#__PURE__*/ l.ref<Window>((() => window) as any),
    ),
    dateRanges: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.array(
        /*#__PURE__*/ l.ref<DateRange>((() => dateRange) as any),
      ),
    ),
  }),
)

export { pattern }

type Window = {
  $type?: 'chat.avails.scheduling.availability#window'

  /**
   * 0=Sunday … 6=Saturday (JS getDay convention).
   */
  day: number

  /**
   * HH:MM 24h, in the record's timezone.
   */
  startTime: string

  /**
   * HH:MM 24h, in the record's timezone.
   */
  endTime: string
}

export type { Window }

const window = /*#__PURE__*/ l.typedObject<Window>(
  $nsid,
  'window',
  /*#__PURE__*/ l.object({
    day: /*#__PURE__*/ l.integer({ minimum: 0, maximum: 6 }),
    startTime: /*#__PURE__*/ l.string(),
    endTime: /*#__PURE__*/ l.string(),
  }),
)

export { window }

type DateRange = {
  $type?: 'chat.avails.scheduling.availability#dateRange'

  /**
   * YYYY-MM-DD
   */
  start: string

  /**
   * YYYY-MM-DD
   */
  end: string
  startTime?: string
  endTime?: string
}

export type { DateRange }

const dateRange = /*#__PURE__*/ l.typedObject<DateRange>(
  $nsid,
  'dateRange',
  /*#__PURE__*/ l.object({
    start: /*#__PURE__*/ l.string(),
    end: /*#__PURE__*/ l.string(),
    startTime: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    endTime: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
  }),
)

export { dateRange }
