/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'chat.avails.scheduling.poll'

export { $nsid }

/** A scheduling poll with date/time options */
type Main = {
  $type: 'chat.avails.scheduling.poll'
  title: string
  description?: string
  dates: string[]
  timeRange: TimeRange
  slotMinutes: number
  timezone: string
  community?: string
  status: 'open' | 'closed' | l.UnknownString
  finalTime?: string
  finalDuration?: number

  /**
   * Slug of the OpenMeet event created when the poll was published. Cleared on unschedule so the OpenMeet event can be deleted.
   */
  openmeetEventSlug?: string

  /**
   * ID of the Google Calendar event created when the poll was scheduled. Cleared on unschedule so the event can be auto-cancelled.
   */
  googleEventId?: string

  /**
   * ID of the Google Calendar the event was inserted into. Paired with googleEventId for cleanup on unschedule.
   */
  googleCalendarId?: string
  notifyAfter?: number
  notifyVia?: 'email' | 'telegram' | l.UnknownString
  notifyEmail?: string
  notifyTelegram?: string

  /**
   * If true, respondents see no other responses on the grid until they submit their own.
   */
  hideResponsesUntilSubmit?: boolean
  createdAt: l.DatetimeString
}

export type { Main }

/** A scheduling poll with date/time options */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    title: l.string({ maxLength: 200 }),
    description: l.optional(l.string({ maxLength: 1000 })),
    dates: l.array(l.string(), { minLength: 1, maxLength: 31 }),
    timeRange: l.ref<TimeRange>((() => timeRange) as any),
    slotMinutes: l.integer({ minimum: 15, maximum: 120 }),
    timezone: l.string({ maxLength: 100 }),
    community: l.optional(l.string({ maxLength: 100 })),
    status: l.string<{ knownValues: ['open', 'closed'] }>(),
    finalTime: l.optional(l.string()),
    finalDuration: l.optional(l.integer({ minimum: 15 })),
    openmeetEventSlug: l.optional(l.string()),
    googleEventId: l.optional(l.string()),
    googleCalendarId: l.optional(l.string()),
    notifyAfter: l.optional(l.integer({ minimum: 1 })),
    notifyVia: l.optional(l.string<{ knownValues: ['email', 'telegram'] }>()),
    notifyEmail: l.optional(l.string()),
    notifyTelegram: l.optional(l.string()),
    hideResponsesUntilSubmit: l.optional(l.boolean()),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type TimeRange = {
  $type?: 'chat.avails.scheduling.poll#timeRange'

  /**
   * HH:MM format
   */
  start: string

  /**
   * HH:MM format
   */
  end: string
}

export type { TimeRange }

const timeRange = l.typedObject<TimeRange>(
  $nsid,
  'timeRange',
  l.object({ start: l.string(), end: l.string() }),
)

export { timeRange }
