/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'chat.avails.scheduling.poll'

export { $nsid }

/** A scheduling poll with date/time options */
type Main = {
  $type: 'chat.avails.scheduling.poll'
  title: string
  description?: string
  dates: string[]
  timeRange: TimeRange
  slotMinutes: number
  timezone: string
  community?: string
  status: 'open' | 'closed' | l.UnknownString
  finalTime?: string
  finalDuration?: number

  /**
   * Video call link for the scheduled meeting (Jitsi, Meet, Zoom, or any http(s) URL). Surfaced in the .ics invite and the finalized banner. Cleared on unschedule, since the link belongs to the meeting rather than the poll.
   */
  meetingUrl?: string

  /**
   * Slug of the OpenMeet event created when the poll was published. Cleared on unschedule so the OpenMeet event can be deleted.
   */
  openmeetEventSlug?: string

  /**
   * ID of the Google Calendar event created when the poll was scheduled. Cleared on unschedule so the event can be auto-cancelled.
   */
  googleEventId?: string

  /**
   * ID of the Google Calendar the event was inserted into. Paired with googleEventId for cleanup on unschedule.
   */
  googleCalendarId?: string
  notifyAfter?: number
  notifyVia?: 'email' | 'telegram' | l.UnknownString
  notifyEmail?: string
  notifyTelegram?: string

  /**
   * If true, respondents see no other responses on the grid until they submit their own.
   */
  hideResponsesUntilSubmit?: boolean
  createdAt: l.DatetimeString
}

export type { Main }

/** A scheduling poll with date/time options */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    title: /*#__PURE__*/ l.string({ maxLength: 200 }),
    description: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 1000 }),
    ),
    dates: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string(), {
      minLength: 1,
      maxLength: 31,
    }),
    timeRange: /*#__PURE__*/ l.ref<TimeRange>((() => timeRange) as any),
    slotMinutes: /*#__PURE__*/ l.integer({ minimum: 15, maximum: 120 }),
    timezone: /*#__PURE__*/ l.string({ maxLength: 100 }),
    community: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 100 }),
    ),
    status: /*#__PURE__*/ l.string<{ knownValues: ['open', 'closed'] }>(),
    finalTime: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    finalDuration: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 15 }),
    ),
    meetingUrl: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string({ maxLength: 500 }),
    ),
    openmeetEventSlug: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    googleEventId: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    googleCalendarId: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    notifyAfter: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.integer({ minimum: 1 }),
    ),
    notifyVia: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.string<{ knownValues: ['email', 'telegram'] }>(),
    ),
    notifyEmail: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    notifyTelegram: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
    hideResponsesUntilSubmit: /*#__PURE__*/ l.optional(
      /*#__PURE__*/ l.boolean(),
    ),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)

type TimeRange = {
  $type?: 'chat.avails.scheduling.poll#timeRange'

  /**
   * HH:MM format
   */
  start: string

  /**
   * HH:MM format
   */
  end: string
}

export type { TimeRange }

const timeRange = /*#__PURE__*/ l.typedObject<TimeRange>(
  $nsid,
  'timeRange',
  /*#__PURE__*/ l.object({
    start: /*#__PURE__*/ l.string(),
    end: /*#__PURE__*/ l.string(),
  }),
)

export { timeRange }
