/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'chat.avails.scheduling.response'

export { $nsid }

/** A participant's availability response to a poll */
type Main = {
  $type: 'chat.avails.scheduling.response'
  poll: l.AtUriString
  name: string
  did?: l.DidString
  email?: string

  /**
   * ISO datetime strings for start of each selected slot
   */
  slots: string[]
  createdAt: l.DatetimeString
}

export type { Main }

/** A participant's availability response to a poll */
const main = /*#__PURE__*/ l.record<'tid', Main>(
  'tid',
  $nsid,
  /*#__PURE__*/ l.object({
    poll: /*#__PURE__*/ l.string({ format: 'at-uri' }),
    name: /*#__PURE__*/ l.string({ maxLength: 100 }),
    did: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ format: 'did' })),
    email: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string({ maxLength: 200 })),
    slots: /*#__PURE__*/ l.array(/*#__PURE__*/ l.string()),
    createdAt: /*#__PURE__*/ l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $type = $nsid
export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main)
export const $build = /*#__PURE__*/ main.build.bind(main)
export const $assert = /*#__PURE__*/ main.assert.bind(main)
export const $check = /*#__PURE__*/ main.check.bind(main)
export const $cast = /*#__PURE__*/ main.cast.bind(main)
export const $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main)
export const $matches = /*#__PURE__*/ main.matches.bind(main)
export const $parse = /*#__PURE__*/ main.parse.bind(main)
export const $safeParse = /*#__PURE__*/ main.safeParse.bind(main)
export const $validate = /*#__PURE__*/ main.validate.bind(main)
export const $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
