/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'chat.avails.scheduling.response'

export { $nsid }

/** A participant's availability response to a poll */
type Main = {
  $type: 'chat.avails.scheduling.response'
  poll: l.AtUriString
  name: string
  did?: l.DidString
  email?: string

  /**
   * ISO datetime strings for start of each selected slot
   */
  slots: string[]
  createdAt: l.DatetimeString
}

export type { Main }

/** A participant's availability response to a poll */
const main = l.record<'tid', Main>(
  'tid',
  $nsid,
  l.object({
    poll: l.string({ format: 'at-uri' }),
    name: l.string({ maxLength: 100 }),
    did: l.optional(l.string({ format: 'did' })),
    email: l.optional(l.string({ maxLength: 200 })),
    slots: l.array(l.string()),
    createdAt: l.string({ format: 'datetime' }),
  }),
)

export { main }

export const $isTypeOf = /*#__PURE__*/ main.isTypeOf.bind(main),
  $build = /*#__PURE__*/ main.build.bind(main),
  $type = /*#__PURE__*/ main.$type
export const $assert = /*#__PURE__*/ main.assert.bind(main),
  $check = /*#__PURE__*/ main.check.bind(main),
  $cast = /*#__PURE__*/ main.cast.bind(main),
  $ifMatches = /*#__PURE__*/ main.ifMatches.bind(main),
  $matches = /*#__PURE__*/ main.matches.bind(main),
  $parse = /*#__PURE__*/ main.parse.bind(main),
  $safeParse = /*#__PURE__*/ main.safeParse.bind(main),
  $validate = /*#__PURE__*/ main.validate.bind(main),
  $safeValidate = /*#__PURE__*/ main.safeValidate.bind(main)
